# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cch < Formula
  desc "cch - interactive helper for project console commands"
  homepage "https://github.com/Goodmain/cch"
  version "0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goodmain/console-command-helper/releases/download/v0.1/cch_darwin_amd64.tar.gz"
      sha256 "aced109efeef45fe24a4a414d7b4e90e43711a7682c0f3b9f70fd71c57538671"

      define_method(:install) do
        bin.install "cch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goodmain/console-command-helper/releases/download/v0.1/cch_darwin_arm64.tar.gz"
      sha256 "369aef4dea21ccb7e71cdde9d76af3fa91308e10fe9f054c98f5699914854835"

      define_method(:install) do
        bin.install "cch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goodmain/console-command-helper/releases/download/v0.1/cch_linux_amd64.tar.gz"
      sha256 "2058b821cd0223200bdb9debeb04c422586a20d9a4854cbb64401b0576936fef"
      define_method(:install) do
        bin.install "cch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goodmain/console-command-helper/releases/download/v0.1/cch_linux_arm64.tar.gz"
      sha256 "58c5adb65c5024a863a4572909ee099c7730ae379b186a4e7e3158bb63501019"
      define_method(:install) do
        bin.install "cch"
      end
    end
  end

  test do
    system "#{bin}/cch --version"
  end
end
